# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

stages:
- stage: Development
  jobs:
  - job: Build
  - job: Unit_Tests
  - job: Static_Analysis
  - job: Publish_Dev
  - job: Functional_Tests

- stage: QA
  jobs:
  - job: Publish_QA
  
- stage: UAT
  jobs:
  - job: Publish_UAT